all:
  children:
    pcs_dell:
      hosts:
        dell:
          ansible_host: 172.0.0.200



        # Barf:
        #   ansible_host: 172.0.0.199
        #   ansible_user: alien
        #   ansible_port: 22
        #   ansible_become: yes
        #   ansible_become_user: sudo
        #   ansible_become_password: !vault |


